### ISSUE TITLE
Upload field error

### ISSUE THREAD

**Issue by x-bull** [Rodgath/Dilaz-Metabox-Plugin#2]
Hi
I am testing your plugin. Could you check upload field? It is not possible to save the post due some errors.

**Comment by Rodgath** [comment]
Fixed. Check now.

**Comment by x-bull** [comment]
Now got an error: Uncaught Error: [] operator not supported for strings in ...\inc\metabox-class.php:844
after changed it to an array `$output = array();` it works properly

**Comment by Rodgath** [comment]
Changing it from `$output = '';` to `$output = array();` will save an empty array if no file is selected. I have checked this with the recent release and `$output = '';` works fine.
